export interface LogEntry {
  id: string;
  timestamp: string;
  model: string;
  prompt: string;
  completion: string;
  latency_ms: number;
  tokens_used: number;
  input_tokens: number;
  output_tokens: number;
  cost_usd: number;
  project_id: string | null;
  user_id: string | null;
  session_id: string | null;
  tags: string[];
}

export interface DailyStat {
  date: string;
  requests: number;
  cost: number;
  tokens: number;
  p50_latency: number;
}

export interface ModelStat {
  model: string;
  requests: number;
  tokens: number;
  cost: number;
  avg_latency: number;
}

// ── 30-day time series ──────────────────────────────────────────────────────

export const DAILY_STATS: DailyStat[] = [
  { date: '2026-05-05', requests: 1473, cost: 3.89,  tokens: 2100000, p50_latency: 1180 },
  { date: '2026-05-06', requests: 1707, cost: 4.51,  tokens: 2430000, p50_latency: 1220 },
  { date: '2026-05-07', requests: 1831, cost: 4.83,  tokens: 2610000, p50_latency: 1190 },
  { date: '2026-05-08', requests: 1725, cost: 4.56,  tokens: 2460000, p50_latency: 1250 },
  { date: '2026-05-09', requests: 1590, cost: 4.20,  tokens: 2265000, p50_latency: 1210 },
  { date: '2026-05-10', requests: 454,  cost: 1.20,  tokens: 647000,  p50_latency: 980  },
  { date: '2026-05-11', requests: 338,  cost: 0.89,  tokens: 481000,  p50_latency: 960  },
  { date: '2026-05-12', requests: 1638, cost: 4.33,  tokens: 2334000, p50_latency: 1200 },
  { date: '2026-05-13', requests: 1913, cost: 5.05,  tokens: 2727000, p50_latency: 1170 },
  { date: '2026-05-14', requests: 1982, cost: 5.23,  tokens: 2825000, p50_latency: 1230 },
  { date: '2026-05-15', requests: 2089, cost: 5.51,  tokens: 2978000, p50_latency: 1215 },
  { date: '2026-05-16', requests: 1787, cost: 4.72,  tokens: 2547000, p50_latency: 1240 },
  { date: '2026-05-17', requests: 490,  cost: 1.29,  tokens: 698000,  p50_latency: 990  },
  { date: '2026-05-18', requests: 391,  cost: 1.03,  tokens: 557000,  p50_latency: 975  },
  { date: '2026-05-19', requests: 1910, cost: 5.04,  tokens: 2722000, p50_latency: 1195 },
  { date: '2026-05-20', requests: 2049, cost: 5.41,  tokens: 2920000, p50_latency: 1185 },
  { date: '2026-05-21', requests: 2187, cost: 5.77,  tokens: 3117000, p50_latency: 1205 },
  { date: '2026-05-22', requests: 2313, cost: 6.11,  tokens: 3296000, p50_latency: 1175 },
  { date: '2026-05-23', requests: 2116, cost: 5.59,  tokens: 3015000, p50_latency: 1220 },
  { date: '2026-05-24', requests: 631,  cost: 1.67,  tokens: 899000,  p50_latency: 1010 },
  { date: '2026-05-25', requests: 498,  cost: 1.31,  tokens: 710000,  p50_latency: 995  },
  { date: '2026-05-26', requests: 2330, cost: 6.15,  tokens: 3320000, p50_latency: 1165 },
  { date: '2026-05-27', requests: 2438, cost: 6.44,  tokens: 3474000, p50_latency: 1180 },
  { date: '2026-05-28', requests: 2587, cost: 6.83,  tokens: 3687000, p50_latency: 1160 },
  { date: '2026-05-29', requests: 2525, cost: 6.67,  tokens: 3599000, p50_latency: 1190 },
  { date: '2026-05-30', requests: 2390, cost: 6.31,  tokens: 3406000, p50_latency: 1200 },
  { date: '2026-05-31', requests: 747,  cost: 1.97,  tokens: 1064000, p50_latency: 1030 },
  { date: '2026-06-01', requests: 570,  cost: 1.51,  tokens: 812000,  p50_latency: 1015 },
  { date: '2026-06-02', requests: 2730, cost: 7.21,  tokens: 3890000, p50_latency: 1150 },
  { date: '2026-06-03', requests: 2871, cost: 7.58,  tokens: 4091000, p50_latency: 1145 },
  { date: '2026-06-04', requests: 1165, cost: 3.08,  tokens: 1660000, p50_latency: 1140 },
];

export const OVERVIEW_STATS = {
  total_requests: 48291,
  total_cost: 127.43,
  avg_latency_ms: 1247,
  total_tokens: 12400000,
  request_change_pct: 18.2,
  cost_change_pct: 14.7,
  latency_change_pct: -5.3,
  token_change_pct: 21.1,
};

// ── Model breakdown ─────────────────────────────────────────────────────────

export const MODEL_STATS: ModelStat[] = [
  { model: 'claude-sonnet-4-6',  requests: 21483, tokens: 4900000, cost: 62.40, avg_latency: 1342 },
  { model: 'gpt-4o',             requests: 14291, tokens: 3100000, cost: 37.20, avg_latency: 1187 },
  { model: 'claude-haiku-4-5',   requests:  8914, tokens: 1800000, cost: 14.60, avg_latency: 834  },
  { model: 'gpt-4o-mini',        requests:  3603, tokens:  600000, cost:  3.23, avg_latency: 612  },
];

// ── Log entries (45 entries, ~48h window) ───────────────────────────────────

export const LOGS: LogEntry[] = [
  {
    id: 'req_a1b2c3',
    timestamp: '2026-06-04T14:52:11Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Summarize the key themes from this quarter\'s customer feedback survey. Focus on product satisfaction and top-requested features.',
    completion: 'The Q2 survey (n=1,847) shows strong product satisfaction (NPS 62, +8 pts QoQ). Top themes: 1) Faster API response times requested by 71% of enterprise respondents. 2) Better observability tooling. 3) Expanded model selection. Churn risk concentrated in SMB segment citing pricing.',
    latency_ms: 1243, input_tokens: 412, output_tokens: 287, tokens_used: 699, cost_usd: 0.006234,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_p9x1', tags: ['summarization', 'prod'],
  },
  {
    id: 'req_d4e5f6',
    timestamp: '2026-06-04T14:49:03Z',
    model: 'gpt-4o',
    prompt: 'Write a PostgreSQL query to find the top 10 users by total spend in the last 30 days, joining the orders and users tables.',
    completion: 'SELECT u.id, u.email, u.name, SUM(o.total_amount) AS total_spend\nFROM users u\nINNER JOIN orders o ON o.user_id = u.id\nWHERE o.created_at >= NOW() - INTERVAL \'30 days\'\n  AND o.status = \'completed\'\nGROUP BY u.id, u.email, u.name\nORDER BY total_spend DESC\nLIMIT 10;',
    latency_ms: 987, input_tokens: 89, output_tokens: 134, tokens_used: 223, cost_usd: 0.002784,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_r2k9', tags: ['sql', 'prod'],
  },
  {
    id: 'req_g7h8i9',
    timestamp: '2026-06-04T14:45:37Z',
    model: 'claude-haiku-4-5',
    prompt: 'Translate the following product description to French, Spanish, and German: "Lightweight wireless earbuds with 30-hour battery life and active noise cancellation."',
    completion: 'FR: Écouteurs sans fil légers avec 30 heures d\'autonomie et réduction active du bruit.\nES: Auriculares inalámbricos ligeros con 30 horas de batería y cancelación activa de ruido.\nDE: Leichte kabellose Ohrhörer mit 30 Stunden Akkulaufzeit und aktiver Geräuschunterdrückung.',
    latency_ms: 612, input_tokens: 67, output_tokens: 98, tokens_used: 165, cost_usd: 0.000624,
    project_id: 'proj_mobile', user_id: 'user_m5p2', session_id: 'sess_t4w7', tags: ['translation', 'prod'],
  },
  {
    id: 'req_j1k2l3',
    timestamp: '2026-06-04T14:41:22Z',
    model: 'gpt-4o-mini',
    prompt: 'Draft a follow-up email to a prospect who attended our demo last week but hasn\'t responded.',
    completion: 'Subject: Quick follow-up from last week\'s demo\n\nHi [Name],\n\nI wanted to check in following our demo on [date]. I know your schedule is busy — happy to answer any questions async or set up a shorter call to walk through the integration specifics.\n\nWould a 20-minute call this week work?\n\nBest,\n[Your name]',
    latency_ms: 534, input_tokens: 45, output_tokens: 112, tokens_used: 157, cost_usd: 0.000118,
    project_id: 'proj_internal', user_id: 'user_s9u4', session_id: 'sess_v1x8', tags: ['email', 'sales'],
  },
  {
    id: 'req_m4n5o6',
    timestamp: '2026-06-04T14:38:09Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Review this TypeScript function for bugs and performance issues:\n\nasync function processItems(items: string[]) {\n  const results = [];\n  for (const item of items) {\n    const r = await fetch(`/api/process/${item}`);\n    results.push(await r.json());\n  }\n  return results;\n}',
    completion: 'Two issues found:\n\n1. **Sequential fetches** — the loop awaits each fetch before starting the next. For n items this is O(n × latency). Fix: use `Promise.all(items.map(item => fetch(...).then(r => r.json())))` to parallelize.\n\n2. **No error handling** — if any fetch fails, the entire function rejects and partial results are lost. Wrap in try/catch or use `Promise.allSettled` if partial success is acceptable.',
    latency_ms: 1567, input_tokens: 134, output_tokens: 198, tokens_used: 332, cost_usd: 0.003972,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_p9x1', tags: ['code-review', 'prod'],
  },
  {
    id: 'req_p7q8r9',
    timestamp: '2026-06-04T14:31:44Z',
    model: 'gpt-4o',
    prompt: 'Analyze the sentiment of these 5 app store reviews and return a JSON array with id and sentiment (positive/negative/neutral).',
    completion: '[\n  { "id": 1, "sentiment": "positive", "score": 0.92 },\n  { "id": 2, "sentiment": "negative", "score": -0.78 },\n  { "id": 3, "sentiment": "positive", "score": 0.65 },\n  { "id": 4, "sentiment": "neutral",  "score": 0.12 },\n  { "id": 5, "sentiment": "negative", "score": -0.54 }\n]',
    latency_ms: 843, input_tokens: 287, output_tokens: 89, tokens_used: 376, cost_usd: 0.003964,
    project_id: 'proj_mobile', user_id: 'user_n7q3', session_id: 'sess_y3z6', tags: ['sentiment', 'prod'],
  },
  {
    id: 'req_s1t2u3',
    timestamp: '2026-06-04T14:27:18Z',
    model: 'claude-haiku-4-5',
    prompt: 'Extract all company names, people, and locations mentioned in this earnings call transcript.',
    completion: 'Companies: Acme Corp, Vertex Systems, Meridian Partners, GlobalTech Inc\nPeople: Sarah Chen (CFO), Marcus Webb (CEO), Dr. Liu Yan (CTO)\nLocations: San Francisco, Austin TX, London UK, Singapore',
    latency_ms: 734, input_tokens: 1847, output_tokens: 67, tokens_used: 1914, cost_usd: 0.004534,
    project_id: 'proj_api', user_id: 'user_m5p2', session_id: 'sess_b2c5', tags: ['ner', 'prod'],
  },
  {
    id: 'req_v4w5x6',
    timestamp: '2026-06-04T14:19:55Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Generate API documentation in OpenAPI 3.0 format for a POST /users endpoint that creates a new user with email, name, and optional role field.',
    completion: 'paths:\n  /users:\n    post:\n      summary: Create a new user\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              type: object\n              required: [email, name]\n              properties:\n                email: { type: string, format: email }\n                name:  { type: string, minLength: 1 }\n                role:  { type: string, enum: [admin, member, viewer], default: member }\n      responses:\n        201: { description: User created }',
    latency_ms: 1789, input_tokens: 98, output_tokens: 213, tokens_used: 311, cost_usd: 0.004092,
    project_id: 'proj_api', user_id: 'user_k2m8', session_id: 'sess_d6e9', tags: ['docs', 'dev'],
  },
  {
    id: 'req_y7z8a1',
    timestamp: '2026-06-04T14:12:33Z',
    model: 'gpt-4o-mini',
    prompt: 'Classify this support ticket into one of: billing, technical, account, general. Ticket: "I was charged twice for my subscription this month."',
    completion: 'billing',
    latency_ms: 298, input_tokens: 48, output_tokens: 3, tokens_used: 51, cost_usd: 0.000019,
    project_id: 'proj_web', user_id: 'user_s9u4', session_id: 'sess_f8g2', tags: ['classification', 'prod'],
  },
  {
    id: 'req_b2c3d4',
    timestamp: '2026-06-04T14:05:47Z',
    model: 'gpt-4o',
    prompt: 'You are a data analyst. Given this CSV of monthly revenue figures, identify the trend and provide a brief forecast for Q3.',
    completion: 'Revenue trend analysis: The data shows consistent MoM growth of 12.3% over the last 6 months, accelerating from 8.1% in H2 2025. Seasonality factor: Q2 historically outperforms by ~7%. Q3 forecast: $4.2M–$4.6M (base case), with upside to $5.1M if current enterprise pipeline converts at historical rates.',
    latency_ms: 1124, input_tokens: 312, output_tokens: 134, tokens_used: 446, cost_usd: 0.005478,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_i3k7', tags: ['analysis', 'internal'],
  },
  {
    id: 'req_e5f6g7',
    timestamp: '2026-06-04T13:58:22Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Write a concise changelog entry for this git diff. Audience: end users, non-technical.',
    completion: '**v2.4.1 — June 2026**\n- Faster page loads: the dashboard now opens 40% quicker on first visit\n- Fixed a bug where exported CSV files showed incorrect date formats in European locales\n- Search now finds partial matches (e.g. searching "invoic" finds "invoices")\n- Minor visual fixes on mobile screens',
    latency_ms: 1087, input_tokens: 723, output_tokens: 112, tokens_used: 835, cost_usd: 0.008313,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_l2m6', tags: ['changelog', 'prod'],
  },
  {
    id: 'req_h8i9j1',
    timestamp: '2026-06-04T13:47:09Z',
    model: 'claude-haiku-4-5',
    prompt: 'Is this text toxic? Reply with only YES or NO.\n\nText: "Your product is absolutely terrible and I want a full refund immediately."',
    completion: 'NO',
    latency_ms: 287, input_tokens: 42, output_tokens: 2, tokens_used: 44, cost_usd: 0.000118,
    project_id: 'proj_api', user_id: 'user_m5p2', session_id: 'sess_n5o1', tags: ['moderation', 'prod'],
  },
  {
    id: 'req_k2l3m4',
    timestamp: '2026-06-04T13:39:54Z',
    model: 'gpt-4o',
    prompt: 'Convert this Python function to idiomatic Rust. Include proper error handling.\n\ndef read_json(path: str) -> dict:\n    with open(path) as f:\n        return json.load(f)',
    completion: 'use std::fs;\nuse std::path::Path;\nuse serde_json::Value;\nuse anyhow::Result;\n\npub fn read_json(path: impl AsRef<Path>) -> Result<Value> {\n    let contents = fs::read_to_string(path)?;\n    let value: Value = serde_json::from_str(&contents)?;\n    Ok(value)\n}',
    latency_ms: 934, input_tokens: 87, output_tokens: 112, tokens_used: 199, cost_usd: 0.002489,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_q8r4', tags: ['code-gen', 'dev'],
  },
  {
    id: 'req_n5o6p7',
    timestamp: '2026-06-04T13:28:31Z',
    model: 'claude-sonnet-4-6',
    prompt: 'A user is asking how to cancel their subscription. Write a helpful, empathetic support response.',
    completion: 'Hi there,\n\nI\'m sorry to hear you\'d like to cancel — I want to make sure this is as smooth as possible.\n\nYou can cancel anytime from Settings → Billing → Cancel Plan. Your access continues until the end of your billing period, and we don\'t charge any cancellation fees.\n\nIf there\'s anything that prompted this decision — pricing, missing features, or something else — I\'d love to hear it. Your feedback genuinely helps us improve.\n\nLet me know if you run into any issues!',
    latency_ms: 1432, input_tokens: 56, output_tokens: 156, tokens_used: 212, cost_usd: 0.002988,
    project_id: 'proj_web', user_id: 'user_s9u4', session_id: 'sess_t3u9', tags: ['support', 'prod'],
  },
  {
    id: 'req_q8r9s1',
    timestamp: '2026-06-04T13:17:08Z',
    model: 'gpt-4o-mini',
    prompt: 'Extract the invoice number and total amount from this text: "Please find attached invoice #INV-2847 for services rendered in May 2026. Total due: $3,420.00"',
    completion: '{"invoice_number": "INV-2847", "total_amount": 3420.00, "currency": "USD"}',
    latency_ms: 412, input_tokens: 67, output_tokens: 34, tokens_used: 101, cost_usd: 0.000076,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_w5x2', tags: ['extraction', 'finance'],
  },
  {
    id: 'req_t2u3v4',
    timestamp: '2026-06-04T13:04:43Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Explain the concept of database connection pooling to a developer who is new to backend development.',
    completion: 'Think of database connections like phone calls to the database — opening one takes time and resources. Without pooling, every request opens a new connection, uses it, and closes it. With connection pooling, you keep a set of connections open and ready ("the pool"), lending them to requests as needed and returning them when done.\n\nKey benefits: faster responses (no connection overhead per request), controlled concurrency (the pool size limits simultaneous DB load), and resilience (idle connections are health-checked).\n\nIn Node.js, libraries like `pg` and Prisma manage pools automatically. The typical pool size is 5–20 connections depending on your workload.',
    latency_ms: 1678, input_tokens: 42, output_tokens: 198, tokens_used: 240, cost_usd: 0.003468,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_y1z5', tags: ['education', 'dev'],
  },
  {
    id: 'req_w5x6y7',
    timestamp: '2026-06-04T12:51:19Z',
    model: 'claude-haiku-4-5',
    prompt: 'Summarize this news article in one sentence.',
    completion: 'The Federal Reserve held interest rates steady at 4.25–4.5% while signaling two potential cuts in late 2026, contingent on continued progress toward its 2% inflation target.',
    latency_ms: 567, input_tokens: 834, output_tokens: 48, tokens_used: 882, cost_usd: 0.001764,
    project_id: 'proj_mobile', user_id: 'user_m5p2', session_id: 'sess_a7b3', tags: ['summarization', 'prod'],
  },
  {
    id: 'req_z8a9b1',
    timestamp: '2026-06-04T12:39:55Z',
    model: 'gpt-4o',
    prompt: 'Generate 5 A/B test hypothesis ideas for improving checkout conversion on an e-commerce site.',
    completion: '1. **One-click checkout** — Hypothesis: reducing form fields from 8 to 2 (saved card + address) will increase conversion by 12–18% for returning users.\n2. **Progress indicator** — Showing "Step 2 of 3" increases completion by reducing abandonment anxiety.\n3. **Guest checkout prominence** — Making guest checkout the primary CTA (not secondary) may lift conversions 8–15% for first-time visitors.\n4. **Trust signals near CTA** — Adding "256-bit encryption" + payment logos directly above the button may reduce cart abandonment.\n5. **Order summary always-visible** — Sticky summary prevents "did I add the right item?" abandonment mid-checkout.',
    latency_ms: 1456, input_tokens: 47, output_tokens: 213, tokens_used: 260, cost_usd: 0.003248,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_c1d8', tags: ['ideation', 'growth'],
  },
  {
    id: 'req_c2d3e4',
    timestamp: '2026-06-04T12:22:44Z',
    model: 'gpt-4o-mini',
    prompt: 'What is the capital of France?',
    completion: 'Paris.',
    latency_ms: 187, input_tokens: 12, output_tokens: 3, tokens_used: 15, cost_usd: 0.000011,
    project_id: null, user_id: 'user_test', session_id: null, tags: ['test'],
  },
  {
    id: 'req_f5g6h7',
    timestamp: '2026-06-04T12:08:17Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Write unit tests for this function using Vitest:\n\nfunction clamp(value: number, min: number, max: number): number {\n  return Math.min(Math.max(value, min), max);\n}',
    completion: 'import { describe, it, expect } from \'vitest\';\nimport { clamp } from \'./utils\';\n\ndescribe(\'clamp\', () => {\n  it(\'returns value when within range\', () => {\n    expect(clamp(5, 0, 10)).toBe(5);\n  });\n  it(\'clamps to min\', () => {\n    expect(clamp(-5, 0, 10)).toBe(0);\n  });\n  it(\'clamps to max\', () => {\n    expect(clamp(15, 0, 10)).toBe(10);\n  });\n  it(\'handles equal min/max\', () => {\n    expect(clamp(5, 7, 7)).toBe(7);\n  });\n});',
    latency_ms: 1234, input_tokens: 87, output_tokens: 178, tokens_used: 265, cost_usd: 0.003468,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_e2f6', tags: ['testing', 'dev'],
  },
  {
    id: 'req_i8j9k1',
    timestamp: '2026-06-04T11:54:33Z',
    model: 'claude-haiku-4-5',
    prompt: 'Score this resume on a scale of 1-10 for a Senior Full Stack Engineer role. Respond with only the number.',
    completion: '7',
    latency_ms: 312, input_tokens: 1247, output_tokens: 2, tokens_used: 1249, cost_usd: 0.002498,
    project_id: 'proj_internal', user_id: 'user_s9u4', session_id: 'sess_g4h1', tags: ['hr', 'internal'],
  },
  {
    id: 'req_l2m3n4',
    timestamp: '2026-06-04T11:41:07Z',
    model: 'gpt-4o',
    prompt: 'I need a regex pattern that matches valid IPv4 addresses.',
    completion: '^(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)$\n\nThis matches:\n- Each octet: 0–255\n- Exactly four octets separated by dots\n- Full string match (anchored)\n\nNote: this validates format only, not routability (e.g. 999.0.0.1 is rejected, but 0.0.0.0 is accepted).',
    latency_ms: 867, input_tokens: 22, output_tokens: 134, tokens_used: 156, cost_usd: 0.001948,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_j7k3', tags: ['code-gen', 'dev'],
  },
  {
    id: 'req_o5p6q7',
    timestamp: '2026-06-04T11:23:51Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Write a compelling LinkedIn post announcing our new Series A funding round of $12M led by Sequoia.',
    completion: 'Thrilled to share that we\'ve raised $12M in Series A funding, led by Sequoia Capital 🚀\n\nWhen we started two years ago with three engineers and an idea, the problem was clear: developers had no visibility into what their LLMs were actually doing in production. Today, 2,400 teams use LLMWatch to observe, debug, and improve their AI applications.\n\nThis funding lets us:\n→ Expand our evals platform (launching Q3)\n→ Grow the team from 12 to 30 by EOY\n→ Build the integrations you\'ve been asking for\n\nTo our users, investors, and team — thank you. The best is ahead.\n\n#AI #LLMOps #Observability #Fundraising',
    latency_ms: 1876, input_tokens: 52, output_tokens: 201, tokens_used: 253, cost_usd: 0.003588,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_m9n2', tags: ['copywriting', 'marketing'],
  },
  {
    id: 'req_r8s9t1',
    timestamp: '2026-06-04T11:09:14Z',
    model: 'gpt-4o-mini',
    prompt: 'Convert 95 Fahrenheit to Celsius.',
    completion: '35°C',
    latency_ms: 198, input_tokens: 14, output_tokens: 5, tokens_used: 19, cost_usd: 0.000014,
    project_id: null, user_id: 'user_test', session_id: null, tags: ['test'],
  },
  {
    id: 'req_u2v3w4',
    timestamp: '2026-06-04T10:54:38Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Perform a security audit of this Express middleware and identify any vulnerabilities.',
    completion: 'Three security issues identified:\n\n**Critical**\n- Line 12: User-supplied `id` interpolated directly into a shell command via `exec()`. This is a command injection vulnerability. Fix: use parameterized APIs or strictly validate/allowlist input.\n\n**High**\n- Line 8: JWT secret loaded from `req.body` rather than environment config. An attacker can forge tokens by supplying their own secret.\n\n**Medium**\n- No rate limiting on this endpoint — susceptible to brute-force attacks. Add `express-rate-limit` with a per-IP limit.',
    latency_ms: 2134, input_tokens: 287, output_tokens: 178, tokens_used: 465, cost_usd: 0.006042,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_p4q8', tags: ['security', 'code-review'],
  },
  {
    id: 'req_x5y6z7',
    timestamp: '2026-06-04T10:38:22Z',
    model: 'claude-haiku-4-5',
    prompt: 'Detect the language of this text: "Die Implementierung des neuen Systems war erfolgreich."',
    completion: 'German (Deutsch)',
    latency_ms: 267, input_tokens: 38, output_tokens: 7, tokens_used: 45, cost_usd: 0.000120,
    project_id: 'proj_api', user_id: 'user_m5p2', session_id: 'sess_r6s3', tags: ['classification', 'prod'],
  },
  {
    id: 'req_a8b9c1',
    timestamp: '2026-06-04T10:21:09Z',
    model: 'gpt-4o',
    prompt: 'Create a Mermaid.js sequence diagram for a user login flow with JWT authentication.',
    completion: '```mermaid\nsequenceDiagram\n    actor User\n    participant FE as Frontend\n    participant API as Auth API\n    participant DB as Database\n\n    User->>FE: Submit credentials\n    FE->>API: POST /auth/login\n    API->>DB: SELECT user WHERE email=?\n    DB-->>API: User record\n    API->>API: bcrypt.compare(password, hash)\n    alt Valid credentials\n        API->>API: jwt.sign({userId}, secret, {expiresIn: \'24h\'})\n        API-->>FE: 200 { token, refreshToken }\n        FE->>FE: Store token in memory\n    else Invalid\n        API-->>FE: 401 Unauthorized\n    end\n```',
    latency_ms: 1567, input_tokens: 34, output_tokens: 198, tokens_used: 232, cost_usd: 0.002898,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_u1v7', tags: ['docs', 'dev'],
  },
  {
    id: 'req_d2e3f4',
    timestamp: '2026-06-04T10:07:45Z',
    model: 'claude-sonnet-4-6',
    prompt: 'What are the main differences between React Server Components and Client Components? Keep it brief.',
    completion: 'Server Components run only on the server — they can access databases/files directly, have no client JS overhead, but cannot use state, effects, or browser APIs. Client Components run in the browser (and are also server-rendered for initial HTML) — they support interactivity, hooks, and events, but add to the JS bundle.\n\nRule of thumb: default to Server Components; add `\'use client\'` only when you need interactivity.',
    latency_ms: 1123, input_tokens: 42, output_tokens: 134, tokens_used: 176, cost_usd: 0.002592,
    project_id: 'proj_web', user_id: 'user_k2m8', session_id: 'sess_w9x4', tags: ['education', 'dev'],
  },
  {
    id: 'req_g5h6i7',
    timestamp: '2026-06-04T09:48:17Z',
    model: 'gpt-4o-mini',
    prompt: 'Generate a random UUID v4.',
    completion: '7f3a1b92-4c8e-4d2f-b631-9e0a57c84d1f',
    latency_ms: 234, input_tokens: 10, output_tokens: 14, tokens_used: 24, cost_usd: 0.000018,
    project_id: null, user_id: 'user_test', session_id: null, tags: ['test'],
  },
  {
    id: 'req_j8k9l1',
    timestamp: '2026-06-04T09:31:44Z',
    model: 'gpt-4o',
    prompt: 'Write a Python script that monitors a directory for new files and prints their names.',
    completion: 'import time\nfrom pathlib import Path\nfrom watchdog.observers import Observer\nfrom watchdog.events import FileSystemEventHandler\n\nclass NewFileHandler(FileSystemEventHandler):\n    def on_created(self, event):\n        if not event.is_directory:\n            print(f"New file: {Path(event.src_path).name}")\n\nif __name__ == "__main__":\n    path = "."\n    handler = NewFileHandler()\n    observer = Observer()\n    observer.schedule(handler, path, recursive=False)\n    observer.start()\n    try:\n        while True:\n            time.sleep(1)\n    except KeyboardInterrupt:\n        observer.stop()\n    observer.join()',
    latency_ms: 1287, input_tokens: 28, output_tokens: 167, tokens_used: 195, cost_usd: 0.002436,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_z5a1', tags: ['code-gen', 'dev'],
  },
  {
    id: 'req_m2n3o4',
    timestamp: '2026-06-03T22:14:33Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Improve the clarity and brevity of this product description while keeping the key benefits.',
    completion: 'Original was 187 words. Revised version (94 words):\n\n"Meet the productivity app built for deep work. Block distractions, time your focus sessions, and track progress — all from one minimal interface. Works offline, syncs across devices, and never sells your data. Used by 40,000+ professionals to reclaim 90 minutes per day."\n\nKey changes: removed redundant phrases ("in order to", "the fact that"), consolidated feature bullets into prose, added social proof to the CTA area, cut passive voice.',
    latency_ms: 1543, input_tokens: 312, output_tokens: 168, tokens_used: 480, cost_usd: 0.005784,
    project_id: 'proj_mobile', user_id: 'user_m5p2', session_id: 'sess_b8c4', tags: ['copywriting', 'prod'],
  },
  {
    id: 'req_p5q6r7',
    timestamp: '2026-06-03T21:47:08Z',
    model: 'claude-haiku-4-5',
    prompt: 'Convert this JSON to a TypeScript interface.',
    completion: 'interface Order {\n  id: string;\n  created_at: string;\n  status: "pending" | "processing" | "shipped" | "delivered";\n  customer: {\n    id: string;\n    email: string;\n    name: string;\n  };\n  items: Array<{\n    sku: string;\n    quantity: number;\n    unit_price: number;\n  }>;\n  total: number;\n  currency: string;\n}',
    latency_ms: 623, input_tokens: 187, output_tokens: 134, tokens_used: 321, cost_usd: 0.000642,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_d2e7', tags: ['code-gen', 'dev'],
  },
  {
    id: 'req_s8t9u1',
    timestamp: '2026-06-03T20:33:21Z',
    model: 'gpt-4o',
    prompt: 'You are a financial advisor. A client has $50k to invest with a 10-year horizon. They have moderate risk tolerance. What allocation would you suggest?',
    completion: 'For a moderate-risk investor with a 10-year horizon, a balanced growth allocation:\n\n**60% Equities** — 40% US total market (VTI), 20% international developed (VXUS)\n**30% Fixed Income** — 20% US bonds (BND), 10% TIPS for inflation protection\n**10% Alternatives** — 5% REITs, 5% commodities (DJP)\n\nKey rationale: 10-year horizon allows equity exposure to recover from downturns. Moderate risk = willing to see -25% in a bad year. Annual rebalancing recommended. This is general guidance — consult a licensed advisor for personalized planning.',
    latency_ms: 1678, input_tokens: 67, output_tokens: 189, tokens_used: 256, cost_usd: 0.003198,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_f1g6', tags: ['finance', 'internal'],
  },
  {
    id: 'req_v2w3x4',
    timestamp: '2026-06-03T19:15:44Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Critique this tagline for a B2B SaaS company: "Empowering teams to leverage synergistic solutions for optimized workflows."',
    completion: 'This tagline has every hallmark of bad B2B copy:\n\n❌ **"Empowering"** — overused, says nothing\n❌ **"Leverage"** — corporate filler verb\n❌ **"Synergistic"** — meaningless buzzword\n❌ **"Optimized workflows"** — vague, not specific to any outcome\n\nThe entire sentence describes process, not value. A prospect reading it cannot answer "what does this company actually do?"\n\nBetter direction: be specific about what problem you solve and for whom. E.g. "Ship software 30% faster. Without the meetings." is worse writing but infinitely more effective.',
    latency_ms: 1345, input_tokens: 56, output_tokens: 178, tokens_used: 234, cost_usd: 0.003192,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_h3i9', tags: ['copywriting', 'marketing'],
  },
  {
    id: 'req_y5z6a7',
    timestamp: '2026-06-03T17:48:11Z',
    model: 'gpt-4o-mini',
    prompt: 'What is 847 × 293?',
    completion: '248,171',
    latency_ms: 223, input_tokens: 16, output_tokens: 8, tokens_used: 24, cost_usd: 0.000018,
    project_id: null, user_id: 'user_test', session_id: null, tags: ['test'],
  },
  {
    id: 'req_b8c9d1',
    timestamp: '2026-06-03T16:22:55Z',
    model: 'claude-haiku-4-5',
    prompt: 'Label these transactions as income or expense:\n1. $2,400 from Acme Corp\n2. $89.99 Adobe Creative Cloud\n3. $14,200 Payroll\n4. $340 AWS bill',
    completion: '1. Income — $2,400\n2. Expense — $89.99\n3. Expense — $14,200\n4. Expense — $340',
    latency_ms: 434, input_tokens: 78, output_tokens: 44, tokens_used: 122, cost_usd: 0.000244,
    project_id: 'proj_internal', user_id: 'user_s9u4', session_id: 'sess_j6k2', tags: ['finance', 'internal'],
  },
  {
    id: 'req_e2f3g4',
    timestamp: '2026-06-03T14:59:38Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Write a Kubernetes deployment manifest for a Node.js API service with 3 replicas, resource limits, and a readiness probe.',
    completion: 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: node-api\n  labels:\n    app: node-api\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: node-api\n  template:\n    metadata:\n      labels:\n        app: node-api\n    spec:\n      containers:\n      - name: node-api\n        image: node-api:latest\n        ports:\n        - containerPort: 3000\n        resources:\n          requests:\n            memory: "128Mi"\n            cpu: "100m"\n          limits:\n            memory: "256Mi"\n            cpu: "500m"\n        readinessProbe:\n          httpGet:\n            path: /health\n            port: 3000\n          initialDelaySeconds: 5\n          periodSeconds: 10',
    latency_ms: 2234, input_tokens: 48, output_tokens: 267, tokens_used: 315, cost_usd: 0.004296,
    project_id: 'proj_api', user_id: 'user_k2m8', session_id: 'sess_l4m8', tags: ['infra', 'dev'],
  },
  {
    id: 'req_h5i6j7',
    timestamp: '2026-06-03T13:34:17Z',
    model: 'gpt-4o',
    prompt: 'Proofread this paragraph and fix any grammar issues: "The company have been operating since 2019 and have grown it\'s team from 5 to over 200 employes. We are proud of the milestones we achieved, and looks forward to continue growing."',
    completion: 'The company **has** been operating since 2019 and **has** grown **its** team from 5 to over 200 **employees**. We are proud of the milestones we **have** achieved and **look** forward to **continuing to grow**.\n\nFixes: subject-verb agreement (company → singular), its/it\'s, "employes" spelling, tense consistency, "continue growing" → "continuing to grow".',
    latency_ms: 934, input_tokens: 98, output_tokens: 134, tokens_used: 232, cost_usd: 0.002898,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_n2o5', tags: ['writing', 'internal'],
  },
  {
    id: 'req_k8l9m1',
    timestamp: '2026-06-03T11:47:52Z',
    model: 'claude-haiku-4-5',
    prompt: 'What is the time complexity of quicksort in the average case?',
    completion: 'O(n log n)',
    latency_ms: 234, input_tokens: 18, output_tokens: 8, tokens_used: 26, cost_usd: 0.000070,
    project_id: 'proj_api', user_id: 'user_n7q3', session_id: 'sess_p8q4', tags: ['education', 'dev'],
  },
  {
    id: 'req_n2o3p4',
    timestamp: '2026-06-03T10:23:09Z',
    model: 'claude-sonnet-4-6',
    prompt: 'Write a regex to validate an email address and explain each component.',
    completion: '^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$\n\nBreakdown:\n- `^` — start of string\n- `[a-zA-Z0-9._%+\\-]+` — local part: alphanumeric + allowed special chars (._%+-), one or more\n- `@` — literal @ symbol\n- `[a-zA-Z0-9.\\-]+` — domain name: alphanumeric + dots/hyphens\n- `\\.` — literal dot\n- `[a-zA-Z]{2,}` — TLD: letters only, 2+ chars (handles .io, .co.uk, .museum)\n- `$` — end of string\n\nCaveat: email validation by regex is imperfect. Only sending a verification email confirms deliverability.',
    latency_ms: 1567, input_tokens: 24, output_tokens: 213, tokens_used: 237, cost_usd: 0.003252,
    project_id: 'proj_api', user_id: 'user_k2m8', session_id: 'sess_r1s6', tags: ['code-gen', 'dev'],
  },
  {
    id: 'req_q5r6s7',
    timestamp: '2026-06-03T09:08:44Z',
    model: 'gpt-4o',
    prompt: 'Summarize the key differences between REST and GraphQL APIs.',
    completion: 'REST uses fixed endpoints per resource (GET /users/1, GET /posts); GraphQL uses a single endpoint with a flexible query language. REST can over-fetch or under-fetch data; GraphQL returns exactly what you request. REST is simpler to cache (HTTP caching); GraphQL caching requires tooling (persisted queries, DataLoader). REST is widely understood and has better tooling maturity; GraphQL shines in complex, interconnected data with many client types. Choose REST for simple CRUD with stable schemas; choose GraphQL when frontend needs vary significantly or N+1 query problems dominate.',
    latency_ms: 1124, input_tokens: 22, output_tokens: 167, tokens_used: 189, cost_usd: 0.002362,
    project_id: 'proj_web', user_id: 'user_n7q3', session_id: 'sess_t4u9', tags: ['education', 'dev'],
  },
  {
    id: 'req_t8u9v1',
    timestamp: '2026-06-02T23:41:18Z',
    model: 'gpt-4o-mini',
    prompt: 'Translate "Hello, how are you?" to Japanese.',
    completion: 'こんにちは、お元気ですか？(Konnichiwa, o-genki desu ka?)',
    latency_ms: 312, input_tokens: 18, output_tokens: 28, tokens_used: 46, cost_usd: 0.000035,
    project_id: 'proj_mobile', user_id: 'user_m5p2', session_id: 'sess_v7w3', tags: ['translation', 'prod'],
  },
  {
    id: 'req_w2x3y4',
    timestamp: '2026-06-02T21:17:55Z',
    model: 'claude-sonnet-4-6',
    prompt: 'You are a startup advisor. Review this one-paragraph pitch for a B2B SaaS company and give actionable feedback.',
    completion: 'Strong elements: the "48h to first insight" metric is concrete and credible. Weak points:\n\n1. **No stated problem** — the pitch leads with solution. Lead with the pain: who wastes time on what, and what does that cost?\n2. **Target customer is vague** — "businesses" is too broad. "Ops managers at e-commerce companies with >$1M ARR" triggers more interest.\n3. **"AI-powered"** adds no signal in 2026 — every tool claims AI. What specifically does the AI do that matters?\n4. **CTA missing** — end with a single ask: demo, trial, or investor intro.\n\nRewrite the first sentence to lead with the pain, and you\'ll hook the right readers immediately.',
    latency_ms: 1734, input_tokens: 178, output_tokens: 213, tokens_used: 391, cost_usd: 0.004908,
    project_id: 'proj_internal', user_id: 'user_h4j1', session_id: 'sess_x5y2', tags: ['strategy', 'internal'],
  },
];
